"""Key tasks of the M2Radar content engine, one row per task, for the Notion kanban.

This file is the single source of truth for the board (`engine/notion_kanban.py` reads it, the
tests validate it). English only. Every task carries a stable `key` (idempotency key in Notion),
the `block` it belongs to, the pipeline `stage` it maps to (engine.state.STAGES or one of the
cross-cutting labels), its `status`, the `owner`, the `evidence` (repo paths, commits, counts)
and a short note. Dynamic evidence (row counts, job counts) is filled in by
`notion_kanban.build_rows()` at apply time from the database it runs against, so the board
reflects the machine it was generated from, never a number typed by hand.

Statuses: Done = shipped and verified · In progress = code exists, data still flowing · Planned =
agreed, not started · Blocked = waiting for a decision or an external input (named in the note).
"""

BLOCKS = ('Data gathering', 'Analysis', 'Script', 'Video', 'Notion & docs', 'Infra & ops', 'Audience')
STATUSES = ('Done', 'In progress', 'Planned', 'Blocked')
OWNERS = ('Fable', 'Misha', 'Max', 'cron', 'Opus/Sonnet agents')
CROSS_STAGES = ('CROSS_CUTTING', 'AUDIENCE_RESEARCH', 'RULES', 'DEPLOY')

# order, key, block, stage, status, owner, evidence, note
TASKS = [
    # ---------------------------------------------------------------- Data gathering
    (10, 'roster-and-snapshots', 'Data gathering', 'DISCOVERED', 'Done', 'cron',
     'roster.py, collect_snapshot.py, cron.sh (Mon/Thu 07:00), 3 snapshots, {n_ingested} unique reel codes',
     'HikerAPI collection of the 100-account core roster; key lives only in /opt/radar/.env.'),
    (20, 'hiker-in-architecture', 'Data gathering', 'VIDEO_METADATA_FETCHED', 'Done', 'Fable',
     'engine/hiker_config.py, engine/providers.py, lib/hiker.py (PRICE_RECEIPT, .meta.json sidecars), fetch_log table',
     'Hiker is a committed provider with receipts and a config check; no key in git.'),
    (30, 'media-watchdog', 'Data gathering', 'MEDIA_FETCHED', 'In progress', 'cron',
     'engine/watchdog.py; {n_pending} newest reels pending (CDN links expired before processing)',
     'Runs after each collection; first non-zero selection expected Monday 2026-09-14 07:00. No paid re-fetch (Misha, 12 Sep).'),
    (40, 'local-asr', 'Data gathering', 'TRANSCRIPTION', 'Done', 'Fable',
     'engine/local_pipeline.py (faster-whisper small int8), transcript_meta.asr_version; {n_transcripts} transcript rows',
     'Local-first, video-by-video, idempotent per asr_version.'),
    (50, 'frame-extraction', 'Data gathering', 'FRAME_EXTRACTION', 'Done', 'Fable',
     'engine/scenes.py (scene>0.30, min 0.4 s) + legacy fixed-9 sampling; {n_frames} frame rows; sha256/exists_ok',
     'Legacy corpus keeps 9 fixed samples; the new detector writes scenes with timecodes.'),
    (60, 'alignment', 'Data gathering', 'ALIGNMENT', 'Done', 'Fable',
     'engine/align.py; beats {n_beats}, scenes {n_scenes}',
     'Transcript beats aligned to scenes where both exist.'),
    (70, 'max-transcripts-import', 'Data gathering', 'TRANSCRIPTION', 'Blocked', 'Max',
     'docs/HANDOFF_MAX_2026-09-12.md §3.1 (import path); Latest branch = mcharniuk1-spec fork',
     'Waiting for Max to export his 1,062 transcripts and 19,808 frames with stable ids.'),
    # ---------------------------------------------------------------- Analysis
    (110, 'transcript-analysis', 'Analysis', 'TRANSCRIPT_ANALYSIS', 'Done', 'Opus/Sonnet agents',
     'engine/prompts/transcript-analysis.md (ta-v1); data/analysis/transcripts/*.json; {n_ta} files',
     'Beats, semantics, interpretation per reel; closed vocabularies from engine/SPEC.md §4.'),
    (120, 'frame-analysis', 'Analysis', 'FRAME_ANALYSIS', 'Done', 'Opus/Sonnet agents',
     'engine/prompts/frame-analysis.md (fa-v1); data/analysis/frames/*.json; {n_fa} files',
     'Shot grammar per sampled frame and per video.'),
    (130, 'scheduled-analysis', 'Analysis', 'TRANSCRIPT_ANALYSIS', 'Done', 'cron',
     'engine/analyze_pending.py + engine/prompts/analyze-pending.md; lock file data/analyze.lock',
     'Unattended batches via claude -p after each watchdog run.'),
    (140, 'features-and-stats', 'Analysis', 'STATISTICAL_ANALYSIS', 'Done', 'Fable',
     'engine/features.py, engine/stats.py; video_features {n_features}, creator_stats {n_creator_stats}; reports/stats/*',
     'Robust z in log space, rate guard play>=100, creator reliability, Spearman + cluster bootstrap.'),
    (150, 'general-analysis-reports', 'Analysis', 'GENERAL_ANALYSIS', 'Done', 'Opus/Sonnet agents',
     'reports/analysis/01-09, reports/final/M2RADAR_ANALYTICAL_REPORT.pdf (132 pages)',
     'Conclusions carry denominators; analysis-ready set is the top of the ranking (I-01).'),
    (160, 'insights', 'Analysis', 'GENERAL_ANALYSIS', 'Done', 'Fable',
     'data/analysis/insights.json, insights table: {n_insights} insights, {n_reliable} RELIABLE',
     'Each insight has metric, n, comparison, supporting codes and confidence.'),
    (170, 'categorization', 'Analysis', 'CATEGORIZATION', 'In progress', 'Fable',
     'Categories DB in Notion ({n_categories} rows); 6 of 13 planned dimensions',
     'Topic/pain/solution/proof/cta/hook covered; narrative, funnel role, positioning, visual dims pending.'),
    (180, 'hypotheses', 'Analysis', 'CONCEPT_GENERATION', 'Done', 'Fable',
     'data/analysis/hypotheses.json ({n_hypotheses}, 14-key scoring), reports/analysis/08-hypotheses.md',
     'Ten selected by score; rejected ones kept with reasons.'),
    (190, 'reference-selection', 'Analysis', 'REFERENCE_SELECTION', 'Done', 'Fable',
     'data/analysis/hypothesis_refs.json ({n_refs} refs), reports/analysis/09-reference-selection.md',
     'Hypothesis-specific, one function per reel, rules R1-R7.'),
    (195, 'production-md-reproduction', 'Analysis', 'STATISTICAL_ANALYSIS', 'Blocked', 'Misha',
     'docs/PRODUCTION_REPRODUCTION_2026-09-12.md',
     'Two PRODUCTION.md numbers do not reproduce; the approved file is not edited, the decision is Misha\'s.'),
    # ---------------------------------------------------------------- Audience
    (210, 'persona-discussion', 'Audience', 'AUDIENCE_RESEARCH', 'Done', 'Opus/Sonnet agents',
     'reports/audience/01-06, docs/AUDIENCE_PERSONAS_2026-09-12.md',
     'Three lenses (corpus, founders web, workers web), two rounds; three personas: Mary, Ray, Marta.'),
    (220, 'reddit-pass', 'Audience', 'AUDIENCE_RESEARCH', 'Done', 'Fable',
     'reports/audience/07-reddit-pass.md (101 threads, 17 subreddits), reddit-pass-2026-09-12.jsonl',
     'First-hand voice of owners and employees; phrasebank, cost anchors, rejected topics.'),
    (230, 'audience-language-rules', 'Audience', 'RULES', 'Done', 'Fable',
     'RULES.md §11, engine/prompts/script-writer.md rule 13, script-reviewer.md check 11',
     'Name the job not the technology; visible human check; monthly cost + break-even; no replacing people.'),
    (240, 'personas-v2', 'Audience', 'AUDIENCE_RESEARCH', 'Done', 'Fable',
     'personas/*.json (3), docs/PERSONAS.md, engine/personas.py (validate, match, doc); Notion Personas DB',
     'Rick 34 (plumbing/HVAC owner), Emma 29 (online business founder), Anna 38 (ops manager): profile + 43-46 interests each, built from the audience data.'),
    (250, 'persona-adaptation-stage', 'Audience', 'CONCEPT_GENERATION', 'In progress', 'Fable',
     'engine/persona_adapt.py (export, run, list), engine/prompts/persona-adapt.md (pa-v1), routing hint in cards.py output',
     'Radar picks -> concept for the persona whose interest list contains the subject; CTA optional; first batch run 13 Sep, re-run on the v3 personas.'),
    (260, 'artefact-library', 'Audience', 'SCRIPT_GENERATION', 'In progress', 'Fable',
     'artefacts/ (10 one-pagers + README); validator warning card.cta.artefact',
     'What a viewer gets for a comment where a CTA is used (optional); each becomes a PDF when its card is approved.'),
    # ---------------------------------------------------------------- Script
    (310, 'cards-v2-pipeline', 'Script', 'CARD_GENERATION', 'Done', 'Fable',
     'engine/cards_v2.py, engine/cards_pipeline.py; cards_v2 {n_cards} rows, card_scenes {n_card_scenes}',
     'Validator + DB persistence + jobs trace CARD_GENERATION -> VIDEO_GENERATION_READY.'),
    (320, 'script-writer-and-reviewer', 'Script', 'SCRIPT_GENERATION', 'Done', 'Opus/Sonnet agents',
     'engine/prompts/script-writer.md (sw-v1 + rule 13), script-reviewer.md (sr-v1 + check 11); reports/analysis/10-script-review-A/B.md',
     'Independent review; verdict per card; script_versions log.'),
    (330, 'cards-v1-ten', 'Script', 'SCRIPT_REVIEW', 'Done', 'Fable',
     'cards/C-2026-09-12-01..10.json, reports/final/M2RADAR_CARD_BOOK.pdf',
     'Rejected by Misha on 12 Sep ("nobody will watch this"): built from insights, not from audience questions. Kept as v1.'),
    (340, 'shoot-list-v2', 'Script', 'CONCEPT_GENERATION', 'Done', 'Fable',
     'docs/SHOOT_LIST_2026-09-13.md',
     'Rejected by Misha on 13 Sep: topics must come from the persona pipeline, not from a hand-written list. Kept as a record.'),
    (345, 'content-blocks-shortlist', 'Script', 'CARD_GENERATION', 'Done', 'Fable',
     'content_blocks.py (9 blocks, tag + regex routing), cards.py (SHORTLIST 15, stage 1 one per block, stage 2 by strength, cap 3), test_cards.py; RULES.md §13',
     'Misha, 13 Sep: blocks replace personas as the selection axis; 15 reels in three stages, he picks 5 (max 2 per block). Test run on the local base: 15/15, all nine blocks covered.'),
    (346, 'block-routing-by-agent', 'Script', 'CATEGORIZATION', 'Done', 'Fable',
     'engine/block_route.py + engine/prompts/block-route.md (br-v1); data/analysis/blocks/*.json; content_blocks.route prefers the agent file',
     'Misha, 13 Sep: routing must work without errors. Agent reads caption + transcript, quotes evidence, writes an "about" line; tags + regex stay the fallback. First full pass over the 580-reel pool started 13 Sep on the server.'),
    (347, 'shortlist-decision-cards', 'Script', 'CONCEPT_GENERATION', 'Done', 'Fable',
     'engine/shortlist_adapt.py + engine/prompts/shortlist-adapt.md (sa-v1); 15 files in data/analysis/shortlist; Notion database Shortlist (15 rows); reports/shortlist/2026-09-13-cards.md; RULES.md §13.6',
     'Misha, 13 Sep evening: a card must show what they shot and what it did, our version under the four-part filter, and the shoot plan by parts. 15 of 15 validated; in run.py step 8 from Monday 14 Sep. The old Notion Cards database is in the trash; cards go to Shortlist under the tool page.'),
    (348, 'block-routing-first-pass', 'Script', 'CATEGORIZATION', 'Done', 'cron',
     '580 br-v1 files, 12 batches, 0 errors; agent disagreed with regex on 313; 153 reels marked off-niche and dropped from the pool (580 -> 427)',
     'Weekly runs route only reels without a file (minutes).'),
    (349, 'evidence-gate', 'Script', 'REFERENCE_SELECTION', 'Done', 'Fable',
     'cards.evidence() + cards._pool(require_evidence); MIN_WORDS 30, frames > 0, language en; ASR language detection instead of forced en; RULES.md §13.7; test_cards.py',
     'Misha, 13 Sep evening: no full transcript + frames -> no card, no reference; English speech only, caption is not enough. 6 of the 15 cards of 13 Sep had full evidence. Pool 427 -> 107 under the gate.'),
    (350, 'cards-from-concepts', 'Script', 'CARD_GENERATION', 'Planned', 'Fable',
     'writer prompt takes data/analysis/concepts/<code>.json as input; strategy.persona + cta filled from the concept',
     'Personas are the example layer inside a block since 13 Sep; first cards after the first approved shortlist.'),
    (360, 'cta-artefacts', 'Script', 'SCRIPT_GENERATION', 'Planned', 'Fable',
     'one-page PDFs: 20-question test sheet, price-sheet template, exception card, decision-minutes template, cost-per-run sheet, four-question AI policy',
     'The comment-keyword CTA is allowed only when the promised artefact exists.'),
    # ---------------------------------------------------------------- Video
    (410, 'storyboard-template-frames', 'Video', 'FRAME_GENERATION', 'Done', 'Fable',
     'engine/storyboard_render.py (Pillow, design tokens), cards/frames/*.png',
     'Template placeholders, no AI imagery, no generated text in images (Misha\'s rule).'),
    (420, 'edl-and-contract', 'Video', 'VIDEO_GENERATION_READY', 'Done', 'Fable',
     'engine/edl.py, studio/remotion/contract.mjs (m2.remotion-edl.v1); cards/edl/*.json + .validation.json',
     'Every card exports a validated PREVIS EDL.'),
    (430, 'remotion-previs-render', 'Video', 'VIDEO_RENDER', 'Done', 'Fable',
     'reports/evidence/ (one real Remotion PREVIS render receipt)',
     'Proves the render path; not a production video.'),
    (440, 'takes-to-render', 'Video', 'VIDEO_RENDER', 'Planned', 'Max',
     'engine/production.py, engine/storage.py; take sidecar -> edl_with_takes -> render -> receipt',
     'Phase 3: real owner footage; contracts and tests exist, no real inputs yet. Ownership offered to Max.'),
    (450, 'storage-supabase-cloudflare', 'Video', 'VIDEO_RENDER', 'Planned', 'Max',
     '.env.example (SUPABASE_*, CLOUDFLARE_*), engine/storage.py',
     'Supabase as canonical store, Cloudflare as delivery only.'),
    (460, 'quality-review-and-publish', 'Video', 'QUALITY_REVIEW', 'Planned', 'Misha',
     'our_posts table feeds results back into selection (used references, closed topics)',
     'Publishing is Misha\'s decision; the radar learns from published results after 12 posts (RULES.md §8).'),
    # ---------------------------------------------------------------- Notion & docs
    (510, 'notion-dashboard-and-dbs', 'Notion & docs', 'NOTION_SYNC', 'Done', 'Fable',
     'engine/notion_sync.py, engine/notion_blocks.py; 7 databases (Runs, Insights, Hypotheses, Cards v2, Reels analysis, Accounts analysis, Categories); ids in data/notion_ids.json',
     'Applied from the server 12 Sep; dashboard rebuilt with Execution section.'),
    (520, 'notion-kanban-and-review', 'Notion & docs', 'NOTION_SYNC', 'Done', 'Fable',
     'engine/notion_kanban.py, engine/kanban_tasks.py; Execution Kanban DB + Execution Review page',
     'Requested by Max on 13 Sep: all key tasks by block and stage with argumentation and execution review.'),
    (530, 'handoff-max', 'Notion & docs', 'CROSS_CUTTING', 'Done', 'Fable',
     'docs/HANDOFF_MAX_2026-09-12.md, reports/final/M2RADAR_HANDOFF_MAX.pdf (29 pages)',
     'What was built, what was taken from Latest and why, open questions.'),
    (540, 'english-docs', 'Notion & docs', 'CROSS_CUTTING', 'In progress', 'Fable',
     'engine/SPEC.md, docs/*.md, reports/* in English; docs/RULES.en.md rendering of the Russian RULES.md',
     'Notion content is English; Russian legacy docs at repo root (RULES.md, PLAN.md, SPEC.md) keep an English rendering beside them.'),
    (550, 'pdf-tooling', 'Notion & docs', 'CROSS_CUTTING', 'Done', 'Fable',
     'tools/pdf/md2pdf.mjs, engine/pdf_build.py, engine/cardbook.py',
     'Headless-Chrome markdown to PDF; used for the analytical report, card book and handoff.'),
    # ---------------------------------------------------------------- Infra & ops
    (610, 'schema-migration', 'Infra & ops', 'CROSS_CUTTING', 'Done', 'Fable',
     'engine/schema.py (schema_migrations), engine/migrate_legacy.py, reports/migration-validation.json',
     'Main SQLite stays canonical; new tables added idempotently; Latest kept as reference.'),
    (620, 'state-tracing', 'Infra & ops', 'CROSS_CUTTING', 'Done', 'Fable',
     'engine/state.py: runs {n_runs}, jobs {n_jobs} ({n_jobs_done} DONE, {n_jobs_failed} FAILED, {n_jobs_skipped} SKIPPED); video_state per code',
     'Every processing step writes a jobs row; refresh_video_state recomputes per-video state.'),
    (630, 'cron-chain', 'Infra & ops', 'DEPLOY', 'Done', 'cron',
     'cron.sh: ff-only pull, config check, run.py (13 legacy steps), watchdog, analyze_pending, features, notion',
     'A failure in a new stage never blocks the old chain.'),
    (640, 'tests', 'Infra & ops', 'CROSS_CUTTING', 'Done', 'Fable',
     'tests/ (pytest, 342 passed locally, 337 on the server), root test_*.py, check.py (23 checks)',
     'Server skips the two batch-format tests that need local analysis input files.'),
    (650, 'server-deploy', 'Infra & ops', 'DEPLOY', 'Done', 'Fable',
     '/opt/radar on m2vps, venv Python 3.12; commits c261744f, 9a39637, 4207c78e, 82206082',
     'Rules v2 (30-day window, shares+saves ladder, author pool, comment CTA) live since 12 Sep.'),
    (660, 'selection-rules-v2', 'Infra & ops', 'RULES', 'Done', 'Misha',
     'RULES.md changelog + §2, cards.py (FRESH_DAYS=30, RANK=hi_intent, author gate), stats.py FORMAT_SIGNAL',
     'Misha\'s four decisions of 12 Sep evening.'),
    (670, 'first-scheduled-run', 'Infra & ops', 'DEPLOY', 'Planned', 'cron',
     'Monday 2026-09-14 07:00 Europe/Vienna; /opt/radar/data/runs/*.log; runs/jobs tables',
     'First run under the new schema and rules; expect the first non-zero watchdog selection.'),
    (680, 'notion-token-rotation', 'Infra & ops', 'CROSS_CUTTING', 'Planned', 'Misha',
     '/opt/radar/.env NOTION_TOKEN',
     'Token appeared once in a subagent tool output on 11 Sep (not written to files); Misha said it is acceptable, rotation still recommended.'),
]
